In [49]:
import pandas as pd
import sklearn

In [28]:
data = pd.DataFrame({
    'temperatura_hoje': [16, 20, 25, 22, 40, 12, 23, 25, 21],
    'choveu': [True, False, False, True, False, True, False, True, False],
    'temperatura_amanha': [19, 23, 27, 25, 42, 15, 25, 28, 23]
})

In [31]:
from sklearn.ensemble import RandomForestRegressor

In [32]:
rf = RandomForestRegressor()

In [33]:
rf.fit(data.drop(['temperatura_amanha'], 1), data['temperatura_amanha'])

RandomForestRegressor(bootstrap=True, ccp_alpha=0.0, criterion='mse',
                      max_depth=None, max_features='auto', max_leaf_nodes=None,
                      max_samples=None, min_impurity_decrease=0.0,
                      min_impurity_split=None, min_samples_leaf=1,
                      min_samples_split=2, min_weight_fraction_leaf=0.0,
                      n_estimators=100, n_jobs=None, oob_score=False,
                      random_state=None, verbose=0, warm_start=False)

In [34]:
rf.predict(data.drop(['temperatura_amanha'], 1))

array([18.78, 23.14, 26.82, 24.91, 37.18, 16.78, 24.86, 27.3 , 23.22])

In [54]:
np.array([[12], [1]])

array([[12],
       [ 1]])

In [60]:
data = pd.DataFrame({
    'temperatura_hoje': [16],
    'choveu': [1],
    })

In [61]:
rf.predict(data)

array([18.78])

In [38]:
joblib.dump(rf, 'model')

['model']